= OpenSSH Server Image
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Buildah: https://buildah.io/[Buildah]
:Fedora: https://getfedora.org/[Fedora]
:Fedora-Silverblue: https://silverblue.fedoraproject.org/[Fedora Silverblue]
:fish: https://fishshell.com/[fish]
:Fedora: https://getfedora.org/[Fedora]
:Git: https://git-scm.com/[Git]
:OpenSSH: https://www.openssh.com/[OpenSSH]
:Podman: https://podman.io/[Podman]
:pre-commit: https://pre-commit.com/[pre-commit]

image:https://img.shields.io/github/workflow/status/jwillikers/openssh-server-image/CI/main[GitHub Workflow Status]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

A container image for running an {OpenSSH} server, built on {Fedora}.

== Synopsis

Image:: https://quay.io/repository/jwillikers/openssh-server[quay.io/jwillikers/openssh-server]

Tags::
* `latest`

Supported architectures::
* `amd64` _(x86_64)_
* `arm` _(armhfp)_
* `arm64` _(aarch64)_

User:: The default user inside the container is named `user`.

Password:: The default password for `user` is `password`.

Cmd:: `["/usr/sbin/sshd", "-D", "-e"]`

Labels::
`io.containers.autoupdate=registry`::: Enables automatic updates when using {Podman} and the _fully-qualified_ image name.

== Quick Start

. To run the OpenSSH server from this image, run the container using {Podman}.
+
[source,sh]
----
➜ podman run --rm -p 2222:22 -dt --name my-openssh-server quay.io/jwillikers/openssh-server:latest
----

. The container should then be accessible using SSH from the local machine.
+
[source,sh]
----
➜ ssh -p 2222 user@127.0.0.1
----

. Enter the default password for the user named `user`, which is `password`.

[NOTE]
====
To access the SSH server from another container, simply run the containers in the same pod.
This doesn't even require port forwarding!
====

== Build

This project uses {Buildah} and {Podman} for building and testing the image.
A set of {pre-commit} checks are readily available to ensure your code is up-to-spec at the time it is committed.
Instructions for setting up a development environment, building the image, and testing the image follow.
These instructions are intended for users of {Fedora-Silverblue}, where the packages `buildah`, `git`, and `podman` are already available.
Moreover, I use the {fish} shell.

. Install the {fish} shell.
+
[source,sh]
----
sudo rpm-ostree install fish
----

. Reboot to finish the installation.
+
[source,sh]
----
systemctl reboot
----

. Clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/openssh-server-image.git
----

. Install {pre-commit}.
+
[source,sh]
----
pip install pre-commit
----

. Change into the project directory.
+
[source,sh]
----
cd ~/Projects/openssh-server-image
----

. Install pre-commit's Git hooks.
+
[source,sh]
----
pre-commit install
----

. Run the shell script to build the image.
+
[source,sh]
----
buildah unshare ~/Projects/openssh-server-image/build.fish
----

. Test the image with the `test.fish` shell script.
+
[source,sh]
----
~/Projects/openssh-server-image/test.fish
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[Asciidoctor]
* {Buildah}
* {Fedora}
* {Fedora-Silverblue}
* {fish}
* {Git
* https://git-scm.com/[Git]
* https://www.linuxfoundation.org/[Linux]
* {OpenSSH}
* {Podman}
* {pre-commit}
* https://www.python.org/[Python]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
