---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run at 1:10 on Sunday
    - cron: "10 1 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image with Buildah
        run: ./openssh-server-image-minimal.sh

      - name: Export the image
        run: podman image save --format oci-archive -o openssh-server.tar localhost/openssh-server

      - uses: actions/upload-artifact@v2
        with:
          name: openssh-server
          path: openssh-server.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: openssh-server

      - name: Load the image
        run: podman image load -i openssh-server.tar

      - name: Run the image and verify the OpenSSH server is available
        run: |
          podman run --name test-container -d -p 2222:22 localhost/openssh-server
          sleep 5
          nc -z localhost 22
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: openssh-server

      - name: Load the image
        run: podman image load -i openssh-server.tar

      - name: Push To quay.io
        id: push-to-quay
        run: buildah push --creds jwillikers+publisher:${{ secrets.REGISTRY_PASSWORD }} openssh-server quay.io/jwillikers/openssh-server:34

