---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 1 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build the image with Buildah
        uses: actions/checkout@v2
        run: ./openssh-server-minimal.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run the image and verify the OpenSSH server is available
        run: |
          podman run --name test-container -d -p 2222:22 openssh-server
          sleep 5
          nc -z localhost 22
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Push To quay.io
        id: push-to-quay
        run: |
          echo "::set-output name=registry-paths::$(buildah push --creds jwillikers:${{ secrets.REGISTRY_PASSWORD }} openssh-server quay.io/jwillikers)"

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
