---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run at 1:10 on Sunday
    - cron: "10 1 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image with Buildah
        run: ./openssh-server-image-minimal.sh -a ${{ matrix.arch }}

      - name: Export the image
        run: podman image save --format oci-archive -o openssh-server-${{ matrix.arch }}.tar localhost/openssh-server

      - uses: actions/upload-artifact@v2
        with:
          name: openssh-server-${{ matrix.arch }}
          path: openssh-server-${{ matrix.arch }}.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: openssh-server-${{ matrix.arch }}

      - name: Load the image
        run: podman image load -i openssh-server-${{ matrix.arch }}.tar

      - name: Run the image and verify the OpenSSH server is available
        run: |
          podman run --name test-container -d -p 2222:22 localhost/openssh-server
          sleep 5
          nc -z localhost 22
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create a manifest
        run: buildah manifest create openssh-server-multiarch:latest

      - uses: actions/download-artifact@v2
        with:
          name: openssh-server-arm64

      - name: Load the arm64 image
        run: podman image load -i openssh-server-arm64.tar
              
      - name: Add the arm64 image to the manifest
        run: buildah manifest add openssh-server-multiarch:latest localhost/openssh-server

      - uses: actions/download-artifact@v2
        with:
          name: openssh-server-amd64

      - name: Load the amd64 image
        run: podman image load -i openssh-server-amd64.tar

      - name: Add the amd64 image to the manifest
        run: buildah manifest add openssh-server-multiarch:latest localhost/openssh-server

      - name: Push latest manifest and images to quay.io
        run: buildah manifest push --all --rm --creds jwillikers+publisher:${{ secrets.REGISTRY_PASSWORD }} openssh-server-multiarch:latest docker://quay.io/jwillikers/openssh-server:latest

      - name: Push tag 34 to quay.io
        run: buildah manifest push --creds jwillikers+publisher:${{ secrets.REGISTRY_PASSWORD }} openssh-server-multiarch:latest docker://quay.io/jwillikers/openssh-server:34
